using System.Text.Json;

namespace RO3.Installer;

public static partial class InstallEngine
{
    public static void ValidateMonoX64(string selected)
    {
        string root = GameSelection.ValidateDirectory(selected);
        using var file = File.OpenRead(Path.Combine(root, "ro3.exe"));
        using var reader = new BinaryReader(file);
        if (file.Length < 128 || reader.ReadUInt16() != 0x5A4D) throw new InvalidDataException("ro3.exe ไม่ใช่ไฟล์ Windows PE ที่รองรับ");
        file.Position = 0x3c;
        uint offset = reader.ReadUInt32();
        if (offset > file.Length - 6) throw new InvalidDataException("Invalid game PE header");
        file.Position = offset;
        if (reader.ReadUInt32() != 0x4550 || reader.ReadUInt16() != 0x8664) throw new InvalidDataException("รุ่นนี้รองรับ RO3 Windows x64 เท่านั้น");
        if (!File.Exists(Path.Combine(root, "ro3_Data", "Managed", "UnityEngine.CoreModule.dll")))
            throw new InvalidDataException("ไม่พบ Unity Mono runtime ที่รองรับในโฟลเดอร์ที่เลือก รุ่นนี้ไม่รองรับ IL2CPP");
    }
    private static bool MutableOwnedFile(string path) => path is "BepInEx/config/AutoTranslatorConfig.ini" or "BepInEx/config/BepInEx.cfg" or "BepInEx/config/gravydevsupreme.xunity.resourceredirector.cfg" or "BepInEx/Translation/th/Text/_AutoGeneratedTranslations.txt" or "BepInEx/config/RO3.TranslationCache/cache.json";

    public static void Uninstall(string selected, IProgress<InstallProgress>? progress = null)
    {
        string target = GameSelection.ValidateDirectory(selected);
        string marker = Path.Combine(target, ".ro3-thai-localization.json");
        if (!File.Exists(marker) || (File.GetAttributes(marker) & FileAttributes.ReparsePoint) != 0 || new FileInfo(marker).Length > 2 * 1024 * 1024) throw new InvalidDataException("ไม่มีข้อมูล ownership ของแพตช์นี้");
        var record = ReadInstallation(target) ?? throw new InvalidDataException("ไม่มีข้อมูล ownership ของแพตช์นี้");
        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var paths = record.Files.Select(entry =>
        {
            if (!names.Add(entry.Path)) throw new InvalidDataException("Duplicate ownership path");
            string full = ResolveSafe(target, entry.Path);
            string? original = OriginalFilePath(record, entry.Path);
            if (original != null && (File.GetAttributes(original) & FileAttributes.ReparsePoint) != 0) throw new InvalidDataException("Reparse backup file");
            if (!File.Exists(full)) return (Entry: entry, Target: full, Original: original);
            bool replaceableRuntimePlugin = entry.Path is "BepInEx/plugins/RO3.ThaiLocalization.Skills.dll" or "BepInEx/plugins/SkillRuntime.Engine.dll";
            if (!MutableOwnedFile(entry.Path) && !replaceableRuntimePlugin && !Sha(full).Equals(entry.Sha256, StringComparison.OrdinalIgnoreCase))
                throw new IOException("ไฟล์ถูกเปลี่ยนภายหลัง จะไม่ลบหรือทับโดยอัตโนมัติ: " + entry.Path);
            return (Entry: entry, Target: full, Original: original);
        }).ToArray();
        string rollback = Path.Combine(Path.GetTempPath(), "ro3-thai-uninstall-" + Guid.NewGuid().ToString("N"));
        var snapshots = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase);
        byte[] oldMarker = File.ReadAllBytes(marker);
        try
        {
            Directory.CreateDirectory(rollback);
            int i = 0;
            foreach (var path in paths)
            {
                if (File.Exists(path.Target))
                {
                    string snapshot = Path.Combine(rollback, (i++).ToString(System.Globalization.CultureInfo.InvariantCulture));
                    File.Copy(path.Target, snapshot, false); snapshots[path.Target] = snapshot;
                }
                else snapshots[path.Target] = null;
            }
            for (i = 0; i < paths.Length; i++)
            {
                ResolveSafe(target, paths[i].Entry.Path);
                if (paths[i].Original != null) File.Copy(paths[i].Original!, paths[i].Target, true);
                else if (File.Exists(paths[i].Target)) File.Delete(paths[i].Target);
                progress?.Report(new InstallProgress(i + 1, paths.Length, paths[i].Entry.Path));
            }
            File.Delete(marker);
        }
        catch (Exception error)
        {
            var rollbackErrors = new List<Exception>();
            foreach (var path in paths)
            {
                try
                {
                    if (snapshots.TryGetValue(path.Target, out string? snapshot) && snapshot != null) File.Copy(snapshot, path.Target, true);
                    else if (File.Exists(path.Target)) File.Delete(path.Target);
                }
                catch (Exception restoreError) { rollbackErrors.Add(restoreError); }
            }
            try { File.WriteAllBytes(marker, oldMarker); } catch (Exception restoreError) { rollbackErrors.Add(restoreError); }
            if (rollbackErrors.Count != 0) throw new AggregateException("ถอนการติดตั้งล้มเหลวและ rollback ไม่ครบ", new[] { error }.Concat(rollbackErrors));
            throw;
        }
        finally { try { if (Directory.Exists(rollback)) Directory.Delete(rollback, true); } catch { } }
        if (record.BackupDirectory != null && Directory.Exists(record.BackupDirectory)) Directory.Delete(record.BackupDirectory, true);
        // Remove only empty manifest-path directories. Preserve logs, user mods and unknown files.
        var folders = new HashSet<string>();
        foreach (var path in paths)
        {
            for (string? folder = Path.GetDirectoryName(path.Target); folder != null && folder != target; folder = Path.GetDirectoryName(folder)) folders.Add(folder);
        }
        foreach (string folder in folders.OrderByDescending(p => p.Length))
        {
            try { Directory.Delete(folder, false); } catch (IOException) { } catch (UnauthorizedAccessException) { }
        }
    }
}
