using System.Text.Json;

namespace RO3.Installer;

public sealed record InstallationRecord(string Version, PayloadFile[] Files, string BackupDirectory, string? TargetProfile = null);

public static partial class InstallEngine
{
    public static void ValidateMonoX64(string selected)
    {
        string root = GameSelection.ValidateDirectory(selected);
        using var file = File.OpenRead(Path.Combine(root, "ro3.exe"));
        using var reader = new BinaryReader(file);
        if (file.Length < 128 || reader.ReadUInt16() != 0x5A4D) throw new InvalidDataException("ro3.exe ไม่ใช่ไฟล์ Windows PE ที่รองรับ");
        file.Position = 0x3c;
        uint offset = reader.ReadUInt32();
        if (offset > file.Length - 6) throw new InvalidDataException("Invalid game PE header");
        file.Position = offset;
        if (reader.ReadUInt32() != 0x4550 || reader.ReadUInt16() != 0x8664) throw new InvalidDataException("รุ่นนี้รองรับ RO3 Windows x64 เท่านั้น");
        if (!File.Exists(Path.Combine(root, "ro3_Data", "Managed", "UnityEngine.CoreModule.dll")))
            throw new InvalidDataException("ไม่พบ Unity Mono runtime ที่รองรับในโฟลเดอร์ที่เลือก รุ่นนี้ไม่รองรับ IL2CPP");
    }
    private static bool MutableOwnedFile(string path) => path is "BepInEx/config/AutoTranslatorConfig.ini" or "BepInEx/config/BepInEx.cfg" or "BepInEx/config/gravydevsupreme.xunity.resourceredirector.cfg" or "BepInEx/Translation/th/Text/_AutoGeneratedTranslations.txt";

    public static string Uninstall(string selected, IProgress<InstallProgress>? progress = null)
    {
        string target = GameSelection.ValidateDirectory(selected);
        string marker = Path.Combine(target, ".ro3-thai-localization.json");
        if (!File.Exists(marker) || (File.GetAttributes(marker) & FileAttributes.ReparsePoint) != 0 || new FileInfo(marker).Length > 2 * 1024 * 1024) throw new InvalidDataException("ไม่มีข้อมูล ownership ของแพตช์นี้");
        var record = JsonSerializer.Deserialize<InstallationRecord>(File.ReadAllText(marker)) ?? throw new InvalidDataException("Invalid ownership record");
        if (record.Files == null || record.Files.Length == 0 || record.Files.Length > 5000) throw new InvalidDataException("Invalid ownership list");
        string backup = Path.GetFullPath(record.BackupDirectory);
        if (Path.GetDirectoryName(backup) != target || !Path.GetFileName(backup).StartsWith(".ro3-thai-backup-", StringComparison.Ordinal) ||
            !Directory.Exists(backup) || (File.GetAttributes(backup) & FileAttributes.ReparsePoint) != 0)
            throw new InvalidDataException("Invalid original backup directory");
        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var paths = record.Files.Select((entry, index) =>
        {
            if (!names.Add(entry.Path)) throw new InvalidDataException("Duplicate ownership path");
            string full = ResolveSafe(target, entry.Path);
            if (!File.Exists(full)) throw new IOException("ไฟล์แพตช์หายไป: " + entry.Path);
            if (!MutableOwnedFile(entry.Path) && !Sha(full).Equals(entry.Sha256, StringComparison.OrdinalIgnoreCase))
                throw new IOException("ไฟล์ถูกเปลี่ยนภายหลัง จะไม่ลบหรือทับโดยอัตโนมัติ: " + entry.Path);
            string original = Path.Combine(backup, index.ToString());
            if (File.Exists(original) && (File.GetAttributes(original) & FileAttributes.ReparsePoint) != 0) throw new InvalidDataException("Reparse backup file");
            return (Entry: entry, Target: full, Original: File.Exists(original) ? original : null);
        }).ToArray();
        // Save the current state, including user-edited config. Retain it after success.
        string saved = Path.Combine(target, ".ro3-thai-uninstall-snapshot-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(saved);
        for (int i = 0; i < paths.Length; i++) File.Copy(paths[i].Target, Path.Combine(saved, i.ToString()), false);
        File.Copy(marker, Path.Combine(saved, "ownership.json"), false);
        try
        {
            for (int i = 0; i < paths.Length; i++)
            {
                ResolveSafe(target, paths[i].Entry.Path);
                if (paths[i].Original != null) File.Copy(paths[i].Original!, paths[i].Target, true);
                else File.Delete(paths[i].Target);
                progress?.Report(new InstallProgress(i + 1, paths.Length, paths[i].Entry.Path));
            }
            File.Delete(marker);
        }
        catch (Exception error)
        {
            var rollbackErrors = new List<Exception>();
            for (int i = 0; i < paths.Length; i++)
            {
                try { File.Copy(Path.Combine(saved, i.ToString()), paths[i].Target, true); }
                catch (Exception restoreError) { rollbackErrors.Add(restoreError); }
            }
            try { File.Copy(Path.Combine(saved, "ownership.json"), marker, true); }
            catch (Exception restoreError) { rollbackErrors.Add(restoreError); }
            if (rollbackErrors.Count != 0) throw new AggregateException("ถอนการติดตั้งล้มเหลว rollback ไม่ครบ เก็บ snapshot ไว้ที่ " + saved, new[] { error }.Concat(rollbackErrors));
            throw;
        }
        // Remove only empty manifest-path directories. Preserve logs, user mods and unknown files.
        var folders = new HashSet<string>();
        foreach (var path in paths)
        {
            for (string? folder = Path.GetDirectoryName(path.Target); folder != null && folder != target; folder = Path.GetDirectoryName(folder)) folders.Add(folder);
        }
        foreach (string folder in folders.OrderByDescending(p => p.Length))
        {
            try { Directory.Delete(folder, false); } catch (IOException) { } catch (UnauthorizedAccessException) { }
        }
        return saved;
    }
}
