"""Build a skills-only fresh dictionary. Does not read legacy translations."""
import sys,csv,json,re
from pathlib import Path
from source_snapshot import read_source
root=Path(__file__).resolve().parents[1]
stage=root/'runtime-build/payload'; config=stage/'BepInEx/config';config.mkdir(parents=True,exist_ok=True)
source={r['ID']:r['English'] for r in read_source(root)}
translations={}
for path in sorted((root/'translations').glob('batch-*.th.json')):translations.update(json.loads(path.read_text(encoding='utf-8')))
blocked={r['ID'] for r in json.loads((root/'translations/semantic-review.json').read_text(encoding='utf-8'))}
rows=[(k,source[k],v) for k,v in translations.items() if k.startswith(('101103','102203','108001')) and k not in blocked]
token=re.compile(r'[$@^]\{\d+\}')
def decoded(s):return s.replace('\\n','\n').replace('\\r','\r').replace('\\t','\t')
def esc(s):return s.replace('\\','\\\\').replace('=','\\=').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')
def regex_literal(s):return re.escape(s).replace("\\\n",r"\n").replace("\\\r",r"\r").replace("\\\t",r"\t")
def literal_pattern(text):
 # A bracketed English skill/status name may appear with either supported bracket style.
 out=[];pos=0
 for m in re.finditer(r'【([^】]+)】|\[([^\]]+)\]',text):
  out.append(regex_literal(text[pos:m.start()]));name=regex_literal((m[1] or m[2]).strip())
  out.append(r'(?:【'+name+r'】|\[ ?'+name+r' ?\])');pos=m.end()
 out.append(regex_literal(text[pos:]));return ''.join(out)
rules=[];canonical={}
for key,en,th in rows:
 en,th=decoded(en),decoded(th)
 if en in canonical and canonical[en]!=th:raise ValueError('Conflicting English key: '+key)
 canonical[en]=th
 if len(en)<45 or not token.search(en):continue
 pieces=[];groups={};pos=0
 for m in token.finditer(en):
  pieces.append(literal_pattern(en[pos:m.start()]));value=m.group()
  if value in groups:pieces.append('\\k<'+groups[value]+'>')
  else:
   name=('s' if value.startswith('^') else 'p')+str(len(groups));groups[value]=name
   body=r'(?:<[^<>\r\n]{1,120}>){0,6}' if value.startswith('^') else r'[+-]?[0-9]{1,12}(?:[.,][0-9]{1,12}){0,3}'
   pieces.append('(?<'+name+'>'+body+')')
  pos=m.end()
 pieces.append(literal_pattern(en[pos:]));pattern=r'\A'+''.join(pieces)+r'\z'
 parts=[];pos=0
 for m in token.finditer(th):
  parts.append(th[pos:m.start()].replace('$','$$'));parts.append('${'+groups[m.group()]+'}');pos=m.end()
 parts.append(th[pos:].replace('$','$$'));replacement=''.join(parts)
 rules.append((key,pattern,replacement.replace('\n','\\n').replace('\r','\\r').replace('\t','\\t')))
with (config/'RO3.SkillTranslations.tsv').open('w',encoding='utf-8',newline='') as f:
 for key,en,th in rows:f.write(key+'\t'+en+'\t'+th+'\n')
with (config/'RO3.SkillRules.tsv').open('w',encoding='utf-8',newline='') as f:
 for cells in rules:f.write('\t'.join(cells)+'\n')
text=stage/'BepInEx/Translation/th/Text';text.mkdir(parents=True,exist_ok=True)
(text/'RO3_Skills_Canonical.txt').write_text(''.join(esc(en)+'='+esc(th)+'\n' for en,th in canonical.items()),encoding='utf-8')
# No XUnity global word rules and no old canonical/alias files.
(text/'_AutoGeneratedTranslations.txt').write_text('',encoding='utf-8')
summary={'fresh_skill_ids':len(rows),'unique_English_descriptions':len(canonical),'numeric_runtime_rules':len(rules),'excluded_semantic_review_ids':sorted(blocked),'legacy_translations_used':False,'online_translation_enabled':False,'game_tested':False}
(root/'docs/partial-skill-payload.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(summary,ensure_ascii=False))
