<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFrameworks>net472;net8.0</TargetFrameworks><LangVersion>latest</LangVersion><Nullable>enable</Nullable></PropertyGroup><ItemGroup Condition="'$(TargetFramework)'=='net472'"><PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" /></ItemGroup></Project>
